### ISSUE TITLE
Repository Aproape Gol :(

### ISSUE THREAD

**Issue by ScourgeNest** [UPB-CS-Rust/teme#12]
Am creat acum repository-ul pentru tema 1 si este aproape gol, lipsesc testele si checker-ul.

**Comment by alexandruradovici** [comment]
Problema a fost la noi, iti sterg acum repository-ul, te rog sa astepti cateva minute si sa accepti tema din nou.

**Comment by alexandruradovici** [comment]
Sa inchizi te rog acest issue daca ti-a mers.
