### ISSUE TITLE
ls -l nu verifica daca printam luna

### ISSUE THREAD

**Issue by Vadim15122003** [UPB-CS-Rust/teme#13]
Dupa enuntul temei ls -l ar trebui sa printeze si luna modificarii, dar testele sunt fara ea, cum trebuie sa facem pana la urma?
La fel cum am zis intrun issue anterior ls_l_r numi trece si singurele diferente pe care mi le arata intre outputul meu si cel care ar trebui sa fie este fisierul pe care insasi acel script il creeaza, cu asta ce fac?

**Comment by alexandruradovici** [comment]
Buna, poti pune te rog un screenshot cu diferenta?

**Comment by Vadim15122003** [comment]
![image](https://github.com/UPB-CS-Rust/teme/assets/50540556/3c4b35a7-0138-4a0d-a6eb-849a83a814eb)
Iar asta e ce am modificat in ls.js ca sa vad diferenta
![image](https://github.com/UPB-CS-Rust/teme/assets/50540556/b3b8e4eb-603a-49d3-ba3f-0f14eebd3e93)

**Comment by alexandruradovici** [comment]
Cred ca am rezolvat problema, testele ar trebui sa fie acum la fel si sa respecte ce face ls.

**Comment by Vadim15122003** [comment]
La ls_all.sh ati uitat sa adaugati folderul cand rulati comanda ls -a pt referinta

**Comment by alexandruradovici** [comment]
Rezolvat, mersi.

**Comment by alexandruradovici** [comment]
Am vazut si noi acum ca nu verificam luna, mai bine spus nu o luam in calcul. Ne poti te rog trimite un pull request? Il vom include dupa ce sa termina perioada de trimitere a temelor, nu va afecta acesta tema.
