### ISSUE TITLE
[rustybox] task-uri bonus

### ISSUE THREAD

**Issue by iulianalexa** [UPB-CS-Rust/teme#14]
pentru task-ul `ls -l`, cum se afiseaza `user` si `group`? din cate inteleg, `std` permite doar aflarea ID-urilor, nu si a numelor asociate acestora, fiind nevoie de crate-ul `libc`.

de asemenea, pentru task-ul `grep`, trebuie sa implementam parser-ul regex de la 0?

**Comment by alexandruradovici** [comment]
> pentru task-ul `ls -l`, cum se afiseaza `user` si `group`? din cate inteleg, `std` permite doar aflarea ID-urilor, nu si a numelor asociate acestora, fiind nevoie de crate-ul `libc`.
> 
Poti lua numele lor din `/etc/passwd`

> de asemenea, pentru task-ul `grep`, trebuie sa implementam parser-ul regex de la 0?
Din cate stiu, testele sunt fara expressii regulate, doar cu string-uri. Gresesc eu?

**Comment by iulianalexa** [comment]
> Din cate stiu, testele sunt fara expressii regulate, doar cu string-uri. Gresesc eu?
in teste apar operatorii `^`, `$` si `*`.

**Comment by alexandruradovici** [comment]
Ma uit imediat.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexandruradovici** [comment]
Asa este, puteti folosi bilbioteca `regex` pentru asta https://docs.rs/regex/latest/regex/
