### ISSUE TITLE
[rustybox] Test ls_all.sh

### ISSUE THREAD

**Issue by RazvanDire** [UPB-CS-Rust/teme#16]
Din cate inteleg eu, testul compara output-ul comenzilor 'ls -a' si 'rustybox ls -a' pe directoare diferite:

```bash
ls -a > output/ls_out

rustybox ls -a `pwd`/lstest &> $outputfile
```

**Comment by alexandruradovici** [comment]
Asa e, s-a rezolvat, multumim. #13 si https://github.com/UPB-CS-Rust/teme/issues/13#issuecomment-1787567040
