### ISSUE TITLE
[rustybox] ls_all_r, ls_all si ls_r

### ISSUE THREAD

**Issue by dandominicstaicu** [UPB-CS-Rust/teme#17]
dupa ultima actualizare a testelor, testele ls_all_r, ls_all si ls_r nu mai functioneaza, desi inainte obtineam punctaj maxim

dupa ce am analizat scripturile noi, am concluzionat

ls_all:
```
ls -a > output/ls_out #  outputul din directorul /tests/

rustybox ls -a `pwd`/lstest &> $outputfile # output in directorul /tests/lstest/

node verify/ls/ls.js output/ls_out $outputfile a > $testfile 2>> $outputfile # verificare
```
pare ca nu compara outputul pe acelasi fisier

ls_r & ls_all_r:
cod extrans din ls_all_r.sh (dar si in ls_r este aceeasi situatie):
```

# echo "modern family" > output/ls_out
# echo "TVshows" >> output/ls_out
# echo "modern family/pritchett" >> output/ls_out
# echo "modern family/dunphy" >> output/ls_out
# echo "modern family/pritchett/jay" >> output/ls_out
# echo "modern family/pritchett/gloria" >> output/ls_out
# echo "modern family/pritchett/joe" >> output/ls_out
# echo "modern family/dunphy/claire" >> output/ls_out
# echo "modern family/dunphy/phil" >> output/ls_out
# echo "." >> output/ls_out
# echo ".." >> output/ls_out
# echo ".hidden" >> output/ls_out
# echo "modern family/." >> output/ls_out
# echo "modern family/.." >> output/ls_out
# echo "modern family/pritchett/." >> output/ls_out
# echo "modern family/pritchett/.." >> output/ls_out
# echo "modern family/dunphy/." >> output/ls_out
# echo "modern family/dunphy/.." >> output/ls_out
# echo "modern family/dunphy/.alex" >> output/ls_out

ls -R -a lstest | grep -v total > output/ls_out

rustybox ls -R -a lstest &> $outputfile
scriptresult=$?
```
outputul generat in noua varianta este **total diferit** de cel care fusese generat cu echo-urile de mai sus

cei care am implementat deja ls pe scheletul vechi, in situatia aceasta ce ar trebui sa facem?
a fost si aici o gresala, asa cum pare sa fie si la ls -a?

**Comment by alexandruradovici** [comment]
Asa este, ar trebui sa fie rezolvat. Uita-te la #13 si https://github.com/UPB-CS-Rust/teme/issues/13#issuecomment-1787567040.

**Comment by alexandruradovici** [comment]
ls -R -a ar trebui sa mearga, vezi https://github.com/UPB-CS-Rust/teme/issues/13#issuecomment-1787454645
