### ISSUE TITLE
Output ls -l

### ISSUE THREAD

**Issue by mariapana** [UPB-CS-Rust/teme#19]
Buna ziua!

Am o nelamurire legata de output-ul corect al comenzii ls -l. Output-ul generat de codul meu si cel generat de comenzile din checker par sa fie identice, insa checker-ul termina executia cu exit code 1.

![image](https://github.com/UPB-CS-Rust/teme/assets/54761687/4d25cba5-d7d4-4fd0-abed-bd07de655ddf)

Nu reusesc sa identific care este problema si daca trebuie sa schimb ceva la implementarea mea. Ma puteti ajuta sa ma lamuresc? Cum ar trebui sa arate output-ul comenzii astfel incat sa convina si checker-ului?

Va multumesc!

**Comment by Vadim15122003** [comment]
Cred ca trebuie sa ai si cuvantul ,,total" cand e fara -R

**Comment by mariapana** [comment]
Am incercat si asa, dar am aceeasi problema.

**Comment by mariapana** [comment]
Am rezolvat, nu imi dadea local, dar era ok cu autograder.

**Comment by alexandruradovici** [comment]
Rezolvat, era din cauza cuvantului total, am modificat testul.

**Comment by mariapana** [comment]
Buna ziua! Acum functioneaza, este totul in regula. Va multumesc!
