### ISSUE TITLE
[rustybox] Probleme cu checkerul

### ISSUE THREAD

**Issue by todi-mih** [UPB-CS-Rust/teme#2]
Daca fac corectarea "manual"(dacă pun comenzile cu argumentele, îmi da rezultatul corect) dar daca fac cu checerul imi da mesaj (pentru fiecare command) : Unknown command: <command>

**Comment by andrei-27** [comment]
Si eu am problema asta

**Comment by alexandruradovici** [comment]
O sa va rog sa publicati un commit pe git (push in repository-ul vostru) sa pot vedea ce face checker-ul.

**Comment by alexandruradovici** [comment]
@andrei-27 la tine tu ai pus codul in `rustybox.rs`, fisier care nu face parte din compilare. Codul trebuie pus in `main.rs` sau fisiere incluse in acesta (folosind `mod nume_fisier`).

Te rog nu mai da commit la fisiere binare, ai compilat *de mana* `rustybox.rs` si ai pus executabilul in folder-ul `src`. Acesta este ignorat de checker.

**Comment by andrei-27** [comment]
am modificat

**Comment by todi-mih** [comment]
eu am facut in main.rs si nu pot sa resolv problema,am facut o commit,astept pentru dmv

**Comment by alexandruradovici** [comment]
@todi-mih pare sa mearga acum, nu?

**Comment by todi-mih** [comment]
@alexandruradovici  am inchercat sa fac un git pull dar imi da acest mesaj : fatal: unable to access 'https://github.com/UPB-CS-Rust/rustybox-todi-mih/': gnutls_handshake() failed: Error in the pull function.

**Comment by todi-mih** [comment]
@alexandruradovici am facut un git pull si acelas lucru,nu imi da punctaj si zice Unknown command: <command>

**Comment by alexandruradovici** [comment]
Screenshot te rog

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by alexandruradovici** [comment]
Ai facut toti pasii de aici https://github.com/UPB-CS-Rust/rustybox-starter/blob/main/README.md?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by todi-mih** [comment]
@alexandruradovici  am rezolvat domnul,nu am facut acest comand export PATH=/home/<your username here>/.cargo/bin:$PATH pentru ca nu a fost la README in VS code ,acum e ok,multumesc si scuze ca v-am deranjat

**Comment by alexandruradovici** [comment]
[like]  Alexandru RADOVICI (24753) reacted to your message:
________________________________
