### ISSUE TITLE
exit code si text pentru comanda invalida

### ISSUE THREAD

**Issue by TrifanBogdan24** [UPB-CS-Rust/teme#25]
Am o intrebata legata de intelegerea enuntului temei. Spre exemplu pentru implementarea comenzii cat :
cat nume_fisiere - Concateneaza continutul fisierelor si il afiseaza la iesirea standard [doc](https://linux.die.net/man/1/cat). In caz de eroare va intoarce valoarea -20 (valoarea 236 va fi afisat in terminal)

Cu ce cod se cere oprirea executiei programului? -20 sau 236? Incercandu-le pe amandoua si ruland "echo $?"  dupa "./main cat file1" (file1 nu exista), ambele afiseaza 236.

{entru "./main cat" , ar trebuie sa se afiseze "Inalid command"?
Dar pentru "./main file1_does_not_exists"?
Dar pentru "./main file1_exists file2_exists file3_does_no_exists file4_exists" ?

Va multumesc anticipat

**Comment by alexandruradovici** [comment]
Pentru codul de eroare, -20 sau 236 sunt aceelasi lucru.

Invalid command ar trebui sa fie doar ca comanda nu exista.
