### ISSUE TITLE
[rustybox] schimbari ls -r si ls -a -r

### ISSUE THREAD

**Issue by iulianalexa** [UPB-CS-Rust/teme#26]
La aceste doua teste au fost facute modificari si nu se mai compara cu fisierul "scris de mana" in script-ul de test, ci cu rezultatul comenzii `ls -R`. Un exemplu de rezultat al `ls -R`:
![image](https://github.com/UPB-CS-Rust/teme/assets/116089722/dc31cd43-f3e8-41eb-a9c6-8c704e9b8085)
(a se observa cele doua puncte de la finalul folderelor)

Deoarece script-ul `ls.js` a fost scris pentru a acoperi cazul path-urilor afisate conform cerintei ("Pentru fisierele/directoarele care nu se gasesc direct in punctul citirii, va afisa calea absoluta, ex: output/test/file."), acesta acum se asteapta sa primeasca nume de fisiere care includ doua puncte:

![image](https://github.com/UPB-CS-Rust/teme/assets/116089722/f8f36baa-817d-4ff9-9fc9-5213e79f5927)
(a se observa modul in care testul pica, desi rezultatul este corect conform cerintei)

Este de precizat ca aceste doua teste treceau inainte de aceste modificari.

**Comment by alexandruradovici** [comment]
Nu cred ca ai fisiere care au : in nume, gresim noi?
