### ISSUE TITLE
fs::extra

### ISSUE THREAD

**Issue by andrei-27** [UPB-CS-Rust/teme#28]
Avem voie sa folosim fs::extra? Stiu ca ati spus dupa ultimul curs ca exista functie de copy recursive, dar nu gasesc nicaieri functia asta, doar in fs::extra ceva similar care nu merge chiar pe toate testele.

**Comment by alexandruradovici** [comment]
Poti folosi orice din std fara sa instalezi alt crate.

Daca te referi la asta https://doc.rust-lang.org/std/fs/struct.Metadata.html#impl-MetadataExt-for-Metadata, da poti folosi.
