### ISSUE TITLE
In autograder, ls -r -l este diferit fata de cel din local?

### ISSUE THREAD

**Issue by AnonimAnonim2245** [UPB-CS-Rust/teme#29]
In output-ul din autograder, imi arata ca nu tb sa pun directoarele originale? Nici ls -l nu da chiar daca sunt la fel

**Comment by AnonimAnonim2245** [comment]
verify:
  drwxr-xr-x runner runner 4096 4 22:40 touch
  verify/touch:
  -rwxr-xr-x runner runner 500 4 22:40 touch_no_create_new.sh
  -rwxr-xr-x runner runner 548 4 22:40 touch_a.sh
  -rw-r--r-- runner runner 785 4 22:40 touch.js
  -rwxr-xr-x runner runner 548 4 22:40 touch_m.sh
  -rwxr-xr-x runner runner 549 4 22:40 touch_simple_exists.sh
  -rwxr-xr-x runner runner 464 4 22:40 touch_simple.sh
  drwxr-xr-x runner runner 4096 4 22:40 mkdir
  verify/mkdir:
  -rwxr-xr-x runner runner 249 4 22:40 mkdir_error.sh
  -rwxr-xr-x runner runner 462 4 22:40 mkdir_path_multiple.sh
  -rwxr-xr-x runner runner 413 4 22:40 mkdir_path.sh
  -rwxr-xr-x runner runner 442 4 22:40 mkdir_multiple.sh
  -rwxr-xr-x runner runner 450 4 22:40 mkdir_spaces.sh
  -rwxr-xr-x runner runner 391 4 22:40 mkdir_simple.sh
  -rw-r--r-- runner runner 301 4 22:40 mkdir.js
  drwxr-xr-x runner runner 4096 4 22:40 ls
  verify/ls:
  -rw-r--r-- runner runner 1170 4 22:40 ls.js
  -rwxr-xr-x runner runner 235 4 22:40 ls_err.sh
  -rwxr-xr-x runner runner 1284 4 22:40 ls_r.sh
  -rw-r--r-- runner runner 1985 4 22:40 ls_old.js
  -rw-r--r-- runner runner 254 4 22:40 readDir.js
  -rwxr-xr-x runner runner 432 4 22:40 ls_simple.sh
  -rwxr-xr-x runner runner 1795 4 22:40 ls_all_r.sh
  -rwxr-xr-x runner runner 487 4 22:40 ls_l_r.sh
  -rwxr-xr-x runner runner 559 4 22:40 ls_dir.sh
  -rwxr-xr-x runner runner 750 4 22:40 ls_all.sh
  -rwxr-xr-x runner runner 467 4 22:40 ls_l.sh
  -rwxr-xr-x runner runner 335 4 22:40 ls_file.sh
  drwxr-xr-x runner runner 4096 4 22:40 mv
  verify/mv:
  -rwxr-xr-x runner runner 1031 4 22:40 mv_simple.sh
  -rwxr-xr-x runner runner 240 4 22:40 mv_error.sh
  -rwxr-xr-x runner runner 1750 4 22:40 mv_dir.sh
  drwxr-xr-x runner runner 4096 4 22:40 grep
  verify/grep:
  -rwxr-xr-x runner runner 599 4 22:40 echo_shell.sh
  -rwxr-xr-x runner runner 567 4 22:40 echo_nodescription.sh
  -rwxr-xr-x runner runner 575 4 22:40 grep_simple.sh
  -rwxr-xr-x runner runner 581 4 22:40 echo_multiple.sh
  drwxr-xr-x runner runner 4096 4 22:40 cp
  verify/cp:
  -rwxr-xr-x runner runner 323 4 22:40 cp_error_dir.sh
  -rwxr-xr-x runner runner 668 4 22:40 cp_simple_rename.sh
  -rwxr-xr-x runner runner 706 4 22:40 cp_r_file.sh
  -rw-r--r-- runner runner 644 4 22:40 cp.js
  -rwxr-xr-x runner runner 245 4 22:40 cp_error_file.sh
  -rwxr-xr-x runner runner 1440 4 22:40 cp_rename_dir.sh
  -rwxr-xr-x runner runner 697 4 22:40 cp_simple_file.sh
  -rwxr-xr-x runner runner 1142 4 22:40 cp_r.sh
  drwxr-xr-x runner runner 4096 4 22:40 cat
  verify/cat:
  -rwxr-xr-x runner runner 460 4 22:40 cat_simple.sh
  -rwxr-xr-x runner runner 678 4 22:40 cat_triple.sh
  -rwxr-xr-x runner runner 253 4 22:40 cat_error.sh
  drwxr-xr-x runner runner 4096 4 22:40 invalid
  verify/invalid:
  -rwxr-xr-x runner runner 442 4 22:40 invalid_command.sh
  -rwxr-xr-x runner runner 453 4 22:40 invalid_chmod.sh
  -rwxr-xr-x runner runner 454 4 22:40 invalid_parameters.sh
  -rwxr-xr-x runner runner 445 4 22:40 invalid_parameters2.sh
  drwxr-xr-x runner runner 4096 4 22:40 pwd
  verify/pwd:
  -rwxr-xr-x runner runner 411 4 22:40 pwd.sh
  drwxr-xr-x runner runner 4096 4 22:40 rm
  verify/rm:
  -rwxr-xr-x runner runner 555 4 22:40 rm_cascade.sh
  -rwxr-xr-x runner runner 390 4 22:40 rm_file.sh
  -rw-r--r-- runner runner 364 4 22:40 rm.js
  -rwxr-xr-x runner runner 399 4 22:40 rm_dir.sh
  -rwxr-xr-x runner runner 412 4 22:40 rm_multiple_mixed.sh
  -rwxr-xr-x runner runner 470 4 22:40 rm_recursive.sh
  -rwxr-xr-x runner runner 879 4 22:40 rm_error_dir.sh
  -rwxr-xr-x runner runner 465 4 22:40 rm_multiple_files.sh
  -rwxr-xr-x runner runner 287 4 22:40 rm_error_exists.sh
  -rwxr-xr-x runner runner 395 4 22:40 rm_empty_dir.sh
  drwxr-xr-x runner runner 4096 4 22:40 echo
  verify/echo:
  -rwxr-xr-x runner runner 425 4 22:40 echo_simple.sh
  -rwxr-xr-x runner runner 448 4 22:40 echo_newline_multiple.sh
  -rwxr-xr-x runner runner 429 4 22:40 echo_spaces.sh
  -rwxr-xr-x runner runner 428 4 22:40 echo_multiple.sh
  -rwxr-xr-x runner runner 434 4 22:40 echo_newline_simple.sh
  drwxr-xr-x runner runner 4096 4 22:40 ln
  verify/ln:
  -rwxr-xr-x runner runner 427 4 22:40 ln_s.sh
  -rw-r--r-- runner runner 1165 4 22:40 ln.js
  -rwxr-xr-x runner runner 263 4 22:40 ln_error.sh
  -rwxr-xr-x runner runner 429 4 22:40 ln_simple.sh
  -rwxr-xr-x runner runner 451 4 22:40 ln_symbolic.sh
  drwxr-xr-x runner runner 4096 4 22:40 rmdir
  verify/rmdir:
  -rwxr-xr-x runner runner 345 4 22:40 rmdir_empty_error.sh
  -rwxr-xr-x runner runner 477 4 22:40 rmdir_multiple.sh
  -rwxr-xr-x runner runner 432 4 22:40 rmdir_link.sh
  -rwxr-xr-x runner runner 422 4 22:40 rmdir_simple.sh
  -rw-r--r-- runner runner 359 4 22:40 rmdir.js
  -rwxr-xr-x runner runner 292 4 22:40 rmdir_exists_error.sh
  drwxr-xr-x runner runner 4096 4 22:40 chmod
  verify/chmod:
  -rw-r--r-- runner runner 480 4 22:40 chmod.js
  -rwxr-xr-x runner runner 682 4 22:40 chmod_del_multiple.sh
  -rwxr-xr-x runner runner 611 4 22:40 chmod_all.sh
  -rwxr-xr-x runner runner 607 4 22:40 chmod_number.sh
  -rwxr-xr-x runner runner 599 4 22:40 chmod_add_multiple.sh
  -rwxr-xr-x runner runner 608 4 22:40 chmod_del_one.sh
  -rwxr-xr-x runner runner 598 4 22:40 chmod_add_one.sh
  -rwxr-xr-x runner runner 610 4 22:40 chmod_user_group.sh
  ls prints extra files/directories
  [
    'drwxr-xr-x runner runner 4096 4 22:40 touch',
    '-rwxr-xr-x runner runner 500 4 22:40 touch_no_create_new.sh',
    '-rwxr-xr-x runner runner 548 4 22:40 touch_a.sh',
    '-rw-r--r-- runner runner 785 4 22:40 touch.js',
    '-rwxr-xr-x runner runner 548 4 22:40 touch_m.sh',
    '-rwxr-xr-x runner runner 549 4 22:40 touch_simple_exists.sh',
    '-rwxr-xr-x runner runner 464 4 22:40 touch_simple.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 mkdir',
    '-rwxr-xr-x runner runner 249 4 22:40 mkdir_error.sh',
    '-rwxr-xr-x runner runner 462 4 22:40 mkdir_path_multiple.sh',
    '-rwxr-xr-x runner runner 413 4 22:40 mkdir_path.sh',
    '-rwxr-xr-x runner runner 442 4 22:40 mkdir_multiple.sh',
    '-rwxr-xr-x runner runner 450 4 22:40 mkdir_spaces.sh',
    '-rwxr-xr-x runner runner 391 4 22:40 mkdir_simple.sh',
    '-rw-r--r-- runner runner 301 4 22:40 mkdir.js',
    'drwxr-xr-x runner runner 4096 4 22:40 ls',
    '-rw-r--r-- runner runner 1170 4 22:40 ls.js',
    '-rwxr-xr-x runner runner 235 4 22:40 ls_err.sh',
    '-rwxr-xr-x runner runner 1284 4 22:40 ls_r.sh',
    '-rw-r--r-- runner runner 1985 4 22:40 ls_old.js',
    '-rw-r--r-- runner runner 254 4 22:40 readDir.js',
    '-rwxr-xr-x runner runner 432 4 22:40 ls_simple.sh',
    '-rwxr-xr-x runner runner 1795 4 22:40 ls_all_r.sh',
    '-rwxr-xr-x runner runner 487 4 22:40 ls_l_r.sh',
    '-rwxr-xr-x runner runner 559 4 22:40 ls_dir.sh',
    '-rwxr-xr-x runner runner 750 4 22:40 ls_all.sh',
    '-rwxr-xr-x runner runner 467 4 22:40 ls_l.sh',
    '-rwxr-xr-x runner runner 335 4 22:40 ls_file.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 mv',
    '-rwxr-xr-x runner runner 1031 4 22:40 mv_simple.sh',
    '-rwxr-xr-x runner runner 240 4 22:40 mv_error.sh',
    '-rwxr-xr-x runner runner 1750 4 22:40 mv_dir.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 grep',
    '-rwxr-xr-x runner runner 599 4 22:40 echo_shell.sh',
    '-rwxr-xr-x runner runner 567 4 22:40 echo_nodescription.sh',
    '-rwxr-xr-x runner runner 575 4 22:40 grep_simple.sh',
    '-rwxr-xr-x runner runner 581 4 22:40 echo_multiple.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 cp',
    '-rwxr-xr-x runner runner 323 4 22:40 cp_error_dir.sh',
    '-rwxr-xr-x runner runner 668 4 22:40 cp_simple_rename.sh',
    '-rwxr-xr-x runner runner 706 4 22:40 cp_r_file.sh',
    '-rw-r--r-- runner runner 644 4 22:40 cp.js',
    '-rwxr-xr-x runner runner 245 4 22:40 cp_error_file.sh',
    '-rwxr-xr-x runner runner 1440 4 22:40 cp_rename_dir.sh',
    '-rwxr-xr-x runner runner 697 4 22:40 cp_simple_file.sh',
    '-rwxr-xr-x runner runner 1142 4 22:40 cp_r.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 cat',
    '-rwxr-xr-x runner runner 460 4 22:40 cat_simple.sh',
    '-rwxr-xr-x runner runner 678 4 22:40 cat_triple.sh',
    '-rwxr-xr-x runner runner 253 4 22:40 cat_error.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 invalid',
    '-rwxr-xr-x runner runner 442 4 22:40 invalid_command.sh',
    '-rwxr-xr-x runner runner 453 4 22:40 invalid_chmod.sh',
    '-rwxr-xr-x runner runner 454 4 22:40 invalid_parameters.sh',
    '-rwxr-xr-x runner runner 445 4 22:40 invalid_parameters2.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 pwd',
    '-rwxr-xr-x runner runner 411 4 22:40 pwd.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 rm',
    '-rwxr-xr-x runner runner 555 4 22:40 rm_cascade.sh',
    '-rwxr-xr-x runner runner 390 4 22:40 rm_file.sh',
    '-rw-r--r-- runner runner 364 4 22:40 rm.js',
    '-rwxr-xr-x runner runner 399 4 22:40 rm_dir.sh',
    '-rwxr-xr-x runner runner 412 4 22:40 rm_multiple_mixed.sh',
    '-rwxr-xr-x runner runner 470 4 22:40 rm_recursive.sh',
    '-rwxr-xr-x runner runner 879 4 22:40 rm_error_dir.sh',
    '-rwxr-xr-x runner runner 465 4 22:40 rm_multiple_files.sh',
    '-rwxr-xr-x runner runner 287 4 22:40 rm_error_exists.sh',
    '-rwxr-xr-x runner runner 395 4 22:40 rm_empty_dir.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 echo',
    '-rwxr-xr-x runner runner 425 4 22:40 echo_simple.sh',
    '-rwxr-xr-x runner runner 448 4 22:40 echo_newline_multiple.sh',
    '-rwxr-xr-x runner runner 429 4 22:40 echo_spaces.sh',
    '-rwxr-xr-x runner runner 428 4 22:40 echo_multiple.sh',
    '-rwxr-xr-x runner runner 434 4 22:40 echo_newline_simple.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 ln',
    '-rwxr-xr-x runner runner 427 4 22:40 ln_s.sh',
    '-rw-r--r-- runner runner 1165 4 22:40 ln.js',
    '-rwxr-xr-x runner runner 263 4 22:40 ln_error.sh',
    '-rwxr-xr-x runner runner 429 4 22:40 ln_simple.sh',
    '-rwxr-xr-x runner runner 451 4 22:40 ln_symbolic.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 rmdir',
    '-rwxr-xr-x runner runner 345 4 22:40 rmdir_empty_error.sh',
    '-rwxr-xr-x runner runner 477 4 22:40 rmdir_multiple.sh',
    '-rwxr-xr-x runner runner 432 4 22:40 rmdir_link.sh',
    '-rwxr-xr-x runner runner 422 4 22:40 rmdir_simple.sh',
    '-rw-r--r-- runner runner 359 4 22:40 rmdir.js',
    '-rwxr-xr-x runner runner 292 4 22:40 rmdir_exists_error.sh',
    'drwxr-xr-x runner runner 4096 4 22:40 chmod',
    '-rw-r--r-- runner runner 480 4 22:40 chmod.js',
    '-rwxr-xr-x runner runner 682 4 22:40 chmod_del_multiple.sh',
    '-rwxr-xr-x runner runner 611 4 22:40 chmod_all.sh',
    '-rwxr-xr-x runner runner 607 4 22:40 chmod_number.sh',
    '-rwxr-xr-x runner runner 599 4 22:40 chmod_add_multiple.sh',
    '-rwxr-xr-x runner runner 608 4 22:40 chmod_del_one.sh',
    '-rwxr-xr-x runner runner 598 4 22:40 chmod_add_one.sh',
    '-rwxr-xr-x runner runner 610 4 22:40 chmod_user_group.sh'
  ]

**Comment by AnonimAnonim2245** [comment]
Pt ls -R -l

**Comment by AnonimAnonim2245** [comment]
drwxr-xr-x runner runner 4096 4 22:40 output
  -rw-r--r-- runner runner 2812 4 22:40 index.ts
  -rw-r--r-- runner runner 0 4 22:40 express
  -rw-r--r-- runner runner 6815 4 22:40 index.js
  drwxr-xr-x runner runner 4096 4 22:40 results
  -rw-r--r-- runner runner 17 4 22:40 README.md
  -rw-r--r-- runner runner 125 4 22:40 errors
  drwxr-xr-x runner runner 4096 4 22:40 verify
  -rw-r--r-- runner runner 203 4 22:40 package.json
  -rw-r--r-- runner runner 10537 4 22:40 package-lock.json
  drwxr-xr-x runner runner 4096 4 22:40 node_modules
  -rwxr-xr-x runner runner 3323 4 22:40 run_all.sh
  ls prints extra files/directories
  [
    'drwxr-xr-x runner runner 4096 4 22:40 output',
    '-rw-r--r-- runner runner 2812 4 22:40 index.ts',
    '-rw-r--r-- runner runner 0 4 22:40 express',
    '-rw-r--r-- runner runner 6815 4 22:40 index.js',
    'drwxr-xr-x runner runner 4096 4 22:40 results',
    '-rw-r--r-- runner runner 17 4 22:40 README.md',
    '-rw-r--r-- runner runner 125 4 22:40 errors',
    'drwxr-xr-x runner runner 4096 4 22:40 verify',
    '-rw-r--r-- runner runner 203 4 22:40 package.json',
    '-rw-r--r-- runner runner 10537 4 22:40 package-lock.json',
    'drwxr-xr-x runner runner 4096 4 22:40 node_modules',
    '-rwxr-xr-x runner runner 3323 4 22:40 run_all.sh'
  ]

**Comment by AnonimAnonim2245** [comment]
Pt ls-l

**Comment by alexandruradovici** [comment]
Singura diferenta intre `ls` de pe sistem si `rustybox ls` este avel string `total` care nu trebuie sa apara.

Autoigrader iti arata ce ai scris tu.
