### ISSUE TITLE
Teste care nu sunt mentionate in enunt

### ISSUE THREAD

**Issue by Vadim15122003** [UPB-CS-Rust/teme#3]
Salut, am vazut ca checkerul are teste precum ls -l, sau grep ce le verifica, iar in enuntul temei nu este mentionat nimic de ele. Trebuie sa le rezolvam?

**Comment by alexandruradovici** [comment]
Acestea fac parte din bonus :)

**Comment by alexandruradovici** [comment]
Am adaugat si enuntul pentru bonus.
