### ISSUE TITLE
In urma unui commit s-a modificat si fisierul "tests" si nu mai functioneaza autograderul.

### ISSUE THREAD

**Issue by TudiG** [UPB-CS-Rust/teme#33]
❌ rm dir
::error::Error: Exit with code: 127 and signal: null
📝 rm empty directory

  /bin/sh: 1: ./run_all.sh: not found
  /bin/sh: 1: ./run_all.sh: not found
  /bin/sh: 1: ./run_all.sh: not found
  /bin/sh: 1: ./run_all.sh: not found
  /bin/sh: 1: ./run_all.sh: not found
  /bin/sh: 1: ./run_all.sh: not found
  /bin/sh: 1: ./run_all.sh: not found

**Comment by alexandruradovici** [comment]
Te rog reseteaza directorul (submodulul) tests la varianta originala. Detalii https://git-scm.com/book/en/v2/Git-Tools-Submodules. Trebuie sa ajunga la aceelasi ID ca in template https://github.com/UPB-CS-Rust/rustybox-starter

**Comment by TudiG** [comment]
> Te rog reseteaza directorul (submodulul) tests la varianta originala. Detalii https://git-scm.com/book/en/v2/Git-Tools-Submodules. Trebuie sa ajunga la aceelasi ID ca in template https://github.com/UPB-CS-Rust/rustybox-starter

Alternativ, este vreo problema daca folosesc alt branch sau punctajul se va da pe branch-ul default? Nu sunt foarte sigur cum se rezolva probleme noi pe care le-am creeat.
