### ISSUE TITLE
Detalii Robin cu prioritati

### ISSUE THREAD

**Issue by Vadim15122003** [UPB-CS-Rust/teme#36]
Salut in enuntul temei scrie ca de fiecare dată când procesul renunță la procesor înainte de a-și depăși timpul alocat, este recompensat cu 1. (in urma unui syscall), In cazul in care avem un syscall dar procesul nu renunta la procesor adica va continua sa ruleze tot el urmatoarea data, in acest caz trebuie sal recompensam cu 1 sau nu penrtru ca nu sa oprit si tot el va rula?

**Comment by alexandruradovici** [comment]
Procesul s-a oprit de buna voie, deci nu va fi penalizat, va fi recompensat. Planificatorul a hotarat ca acest proces sa continue.
