### ISSUE TITLE
CFS Virtual Time pentru procesele noi

### ISSUE THREAD

**Issue by Vadim15122003** [UPB-CS-Rust/teme#37]
Salut care ar trebui sa fie virtualtimeul pentru un process nou creat cu fork?
Dupa primele teste am ajuns la concluzia ca ar trebui sal mosteneasca pe cel al parintelui (inclusiv + operatia de fork), insa la testele de la sfarsit nu mai merge asa si nici nu reusesc sa gasesc o alta explicatie cum ar ajunge sa aiba acel virtualtime ca in teste
![image](https://github.com/UPB-CS-Rust/teme/assets/50540556/e8c2bd82-0dbc-406b-9085-15f7905cc5e7)

**Comment by alexandruradovici** [comment]
Timpul de `vruntime` al unui nou proces este timpul minim de `vruntime` existent in lista de procese.
