### ISSUE TITLE
CFS Timpul de rulare

### ISSUE THREAD

**Issue by Vadim15122003** [UPB-CS-Rust/teme#38]
![image](https://github.com/UPB-CS-Rust/teme/assets/50540556/40ee3e90-058b-4f29-a475-5e3deacba939)
Nu inteleg cum in acest test de la 10 timpul total si un singur process ar trebui sa se ruleze doar 4 unitati de timp, la fel in inca cateva teste mai sunt cazuri ca pt 10 total si 2 processe se cere sa se ruleze pentru 4 unitati

**Comment by alexandruradovici** [comment]
Te rog sa te uiti la documentatia functiei care creaza un scheduler cfs nou:

https://github.com/UPB-CS-Rust/process-scheduler-starter/blob/3a250c86092b2551f5fbe0fb337140dba0935a28/scheduler/src/lib.rs#L55-60

Ai acolo `minimum_remaining_timeslice`, adica timpul minim ramas pentru a preempta procesul. Daca timpul ramas din quanta de timp este mai mare decat acesta, procesul va fi replanificat folosind timpul ramas.
