### ISSUE TITLE
[rustybox]Probleme cu checkerul pe M1

### ISSUE THREAD

**Issue by tiberiugila** [UPB-CS-Rust/teme#4]
lucrez de pe Mac M1 in zsh...cand rulez pwd de mana imi afiseaza dar pe ./run_all.sh primesc 0 puncte

**Comment by alexandruradovici** [comment]
Ne uitam

**Comment by alexandruradovici** [comment]
In codespace merge?

**Comment by tiberiugila** [comment]
Am rezolvat astazi la laborator,multumesc

**Comment by alexandruradovici** [comment]
Cum?

**Comment by tiberiugila** [comment]
nu,mi-ati spus sa testez cu echo f1 f2 parca si ca primesc punctajul in repo ulterior
