### ISSUE TITLE
Avem voie sa modificam trait-ul Process din scheduler.rs?

### ISSUE THREAD

**Issue by Alexe1289** [UPB-CS-Rust/teme#43]
Am adaugat trait bound-ul ```Send``` si alte functii. Ce reprezinta "timpul de executie al apelului de sistem", mai exact campul SYSCALL de mai jos? Si cum ne putem da seama cat timp trece intre 2 iteratii : 
![image](https://github.com/UPB-CS-Rust/teme/assets/119881489/a07bab14-104f-4186-a89d-e68951a4cc38)

**Comment by alexandruradovici** [comment]
As vrea sa vad toata eroarea.

**Comment by alexandruradovici** [comment]
Am inteles problema, poti face modificarea, ne poti da un pull request pe template cu ea?

Te rog pune si aici modificarea pe care ai facut-o.

**Comment by Alexe1289** [comment]
![image](https://github.com/UPB-CS-Rust/teme/assets/119881489/a295712b-f453-4ea9-a755-7c1035150e44)
Am adaugat field-ul ```:Send``` pentru trait ul Process din scheduler.rs. Deci pana la urma e ok asa?

**Comment by Alexe1289** [comment]
Am rezolvat si fara trait-ul Send
