### ISSUE TITLE
[scheduler] Sleep timestamp

### ISSUE THREAD

**Issue by D9nni** [UPB-CS-Rust/teme#45]
Cum ar trebui sa stim cat timp a trecut de cand s-a dat sleep unui proces pana in prezent, ca sa il trecem in Ready?

**Comment by alexandruradovici** [comment]
La panificarea unui process ii spui cate unitati de timp poate rula. Un proces se opreste daca:
- i-a expirat timpul, deci a rulat cat i-a spus tu ca poate rula
- face un apel de sistem si iti spune cat timp i-a mai ramas

Va trebui mereu sa contorizezi folosind aceste doua informatii cat timp a trecut pe procesor.
