### ISSUE TITLE
[scheduler] Test fork_3 output gresit

### ISSUE THREAD

**Issue by v-grigore** [UPB-CS-Rust/teme#50]
![image](https://github.com/UPB-CS-Rust/teme/assets/70589580/1d28bceb-7e0e-4641-b94d-7216c8f9a4cd)
Procesul 1 primeste syscall Exit, dar in ref procesul 3 continua executia.

**Comment by alexandruradovici** [comment]
Ce e scris cu rosu e corect, cu verde e ce ai scris tu.

Procesul 1 iese si scheduler-ul raporteaza Panic.
