### ISSUE TITLE
[scheduler] PartialOrd si Add

### ISSUE THREAD

**Issue by v-grigore** [UPB-CS-Rust/teme#57]
Trebuie implementat PartialOrd chiar daca nu folosim trait-ul?

**Comment by v-grigore** [comment]
Aceeasi intrebare, dar pentru trait-ul Add la Cfs

**Comment by alexandruradovici** [comment]
Pentru priority queue nu trebuie daca nu faci niciodata compararea prioritatilor.

Pentru cfs, nu aveti cum sa nu il folositi. Trebuie sa adunati vruntime si trebuie sa comparati procesele.

**Comment by v-grigore** [comment]
In implementare nu am folosit trait-ul Add. Mai trebuie sa il implementez (chiar daca nu il folosesc) sau pot lasa asa?

**Comment by alexandruradovici** [comment]
L-ai folosit la https://github.com/UPB-CS-Rust/process-scheduler-v-grigore/blob/6d16f7c1593af81612d098c02cb110abc89e5b64/scheduler/src/schedulers/cfs.rs#L294 (poti vedea doar tu acest link). Aici aduni un numar la vruntime-ul procesului.
