### ISSUE TITLE
[scheduler] Nelamurire legata de forkul pentru cfs

### ISSUE THREAD

**Issue by LepinzeanStefan** [UPB-CS-Rust/teme#58]
Am o nelamurire la unele teste. Atunci cand un fork este apelat, pare ca procesul nou creat primeste vruntime=PPID, ceea ce mi se pare ciudat. Este intentionat acest lucru sau inteleg eu ceva gresit? Am adaugat si o poza cu unul dintre acele teste.
![screenshot](https://github.com/UPB-CS-Rust/teme/assets/118962702/85b3e2ea-0419-41af-bae7-cd746cf3cdd9)

**Comment by alexandruradovici** [comment]
Procesul nou primeste vruntime-ul cel mai mic din lista de procese.

**Comment by alexandruradovici** [comment]
Vezi si #37.
