### ISSUE TITLE
ls -l

### ISSUE THREAD

**Issue by Vadim15122003** [UPB-CS-Rust/teme#6]
![image](https://github.com/UPB-CS-Rust/teme/assets/50540556/413cb0b2-793d-42e7-a8ea-0429df0d530d)

Am modificat scriptul sami arate ce diferente sunt intre rularea comenzii mele si cea efectuata de script,
Comanda pare sa mearga bine daca o rulez de mana pe alte directoare sau local,
Testul ala il pica , nu e din cauza ca acele fisiere se modifica in timpul executarii testului?

**Comment by alexandruradovici** [comment]
Ne uitam...
