### ISSUE TITLE
[scheduler] Cum pot face debug pentru ceva ce se intampla intre apeluri de functii ale schedulerului?

### ISSUE THREAD

**Issue by AnneOnciulescu** [UPB-CS-Rust/teme#62]
In testele ce tin de wait(event), am dat de problema in care (cred) ca ceva cicleaza, insa dupa ce am urmarit pas cu pas flow ul programului am descoperit ca totul functioneaza corespunzator pana la iesirea din next + list de dinaintea unui stop ptr Syscall::Wait(event). Procesele trimise catre list sunt ok (inclusiv timings), insa dupa terminarea apelului de list, nu imi mai intra in stop (deloc). Cum pot face debugging pe ce se intampla intre apelul lui list si apelul lui stop (syscall wait event)?

**Comment by alexandruradovici** [comment]
Poti pune println!-uri peste tot, inclusiv in runner. Eu as copia testul in functia main si as rula cu cargo run sau cu depanatorul din VS Code.
