### ISSUE TITLE
[rustybox] nightly

### ISSUE THREAD

**Issue by alx-sima** [UPB-CS-Rust/teme#8]
Putem folosi toolchainul nightly? (pentru std::fs::FileTimes)

**Comment by alexandruradovici** [comment]
Nu, doar stable.

**Comment by iulianalexa** [comment]
se poate verifica daca exista vreun mod de a modifica timpii de acces/modificare ai unui fisier pentru a implementa touch, fara a folosi functii din crate-uri externe sau din nightly rust si fara a adauga continut nou la acesta? am incercat sa caut dar nu am gasit nimic

**Comment by alexandruradovici** [comment]
Deschiderea unul fisier va modifica timpii de access.
